package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.BusinessType;
import vn.com.vti.springexam.entity.BusinessTypeExample;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    long countByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByPrimaryKey(String businessTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    List<BusinessType> selectByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    BusinessType selectByPrimaryKey(String businessTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExampleSelective(@Param("record") BusinessType record, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExample(@Param("record") BusinessType record, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKey(BusinessType record);
}