package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.CardCompany;
import vn.com.vti.springexam.entity.CardCompanyExample;

public interface CardCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    long countByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByPrimaryKey(String cardCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insert(CardCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insertSelective(CardCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    List<CardCompany> selectByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    CardCompany selectByPrimaryKey(String cardCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExampleSelective(@Param("record") CardCompany record, @Param("example") CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExample(@Param("record") CardCompany record, @Param("example") CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKeySelective(CardCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKey(CardCompany record);
}