package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Questionnaire;
import vn.com.vti.springexam.entity.QuestionnaireExample;

public interface QuestionnaireMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    long countByExample(QuestionnaireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByExample(QuestionnaireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int deleteByPrimaryKey(String questionnaireId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insert(Questionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int insertSelective(Questionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    List<Questionnaire> selectByExample(QuestionnaireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    Questionnaire selectByPrimaryKey(String questionnaireId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExampleSelective(@Param("record") Questionnaire record, @Param("example") QuestionnaireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByExample(@Param("record") Questionnaire record, @Param("example") QuestionnaireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKeySelective(Questionnaire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    int updateByPrimaryKey(Questionnaire record);
}