package vn.com.vti.springexam.entity;

import java.util.ArrayList;
import java.util.List;

public class CardCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public CardCompanyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardCompanyIdIsNull() {
            addCriterion("card_company_id is null");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdIsNotNull() {
            addCriterion("card_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdEqualTo(String value) {
            addCriterion("card_company_id =", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdNotEqualTo(String value) {
            addCriterion("card_company_id <>", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdGreaterThan(String value) {
            addCriterion("card_company_id >", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("card_company_id >=", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdLessThan(String value) {
            addCriterion("card_company_id <", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("card_company_id <=", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdLike(String value) {
            addCriterion("card_company_id like", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdNotLike(String value) {
            addCriterion("card_company_id not like", value, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdIn(List<String> values) {
            addCriterion("card_company_id in", values, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdNotIn(List<String> values) {
            addCriterion("card_company_id not in", values, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdBetween(String value1, String value2) {
            addCriterion("card_company_id between", value1, value2, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyIdNotBetween(String value1, String value2) {
            addCriterion("card_company_id not between", value1, value2, "cardCompanyId");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameIsNull() {
            addCriterion("card_company_name is null");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameIsNotNull() {
            addCriterion("card_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameEqualTo(String value) {
            addCriterion("card_company_name =", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameNotEqualTo(String value) {
            addCriterion("card_company_name <>", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameGreaterThan(String value) {
            addCriterion("card_company_name >", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("card_company_name >=", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameLessThan(String value) {
            addCriterion("card_company_name <", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("card_company_name <=", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameLike(String value) {
            addCriterion("card_company_name like", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameNotLike(String value) {
            addCriterion("card_company_name not like", value, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameIn(List<String> values) {
            addCriterion("card_company_name in", values, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameNotIn(List<String> values) {
            addCriterion("card_company_name not in", values, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameBetween(String value1, String value2) {
            addCriterion("card_company_name between", value1, value2, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andCardCompanyNameNotBetween(String value1, String value2) {
            addCriterion("card_company_name not between", value1, value2, "cardCompanyName");
            return (Criteria) this;
        }

        public Criteria andPrefectureIsNull() {
            addCriterion("prefecture is null");
            return (Criteria) this;
        }

        public Criteria andPrefectureIsNotNull() {
            addCriterion("prefecture is not null");
            return (Criteria) this;
        }

        public Criteria andPrefectureEqualTo(String value) {
            addCriterion("prefecture =", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureNotEqualTo(String value) {
            addCriterion("prefecture <>", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureGreaterThan(String value) {
            addCriterion("prefecture >", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureGreaterThanOrEqualTo(String value) {
            addCriterion("prefecture >=", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureLessThan(String value) {
            addCriterion("prefecture <", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureLessThanOrEqualTo(String value) {
            addCriterion("prefecture <=", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureLike(String value) {
            addCriterion("prefecture like", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureNotLike(String value) {
            addCriterion("prefecture not like", value, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureIn(List<String> values) {
            addCriterion("prefecture in", values, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureNotIn(List<String> values) {
            addCriterion("prefecture not in", values, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureBetween(String value1, String value2) {
            addCriterion("prefecture between", value1, value2, "prefecture");
            return (Criteria) this;
        }

        public Criteria andPrefectureNotBetween(String value1, String value2) {
            addCriterion("prefecture not between", value1, value2, "prefecture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_company
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 12 16:45:37 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_company
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}