package vn.com.vti.springexam.entity;

public class CardCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_company.card_company_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String cardCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_company.card_company_name
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String cardCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_company.prefecture
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String prefecture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_company.card_company_id
     *
     * @return the value of card_company.card_company_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getCardCompanyId() {
        return cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_company.card_company_id
     *
     * @param cardCompanyId the value for card_company.card_company_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setCardCompanyId(String cardCompanyId) {
        this.cardCompanyId = cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_company.card_company_name
     *
     * @return the value of card_company.card_company_name
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getCardCompanyName() {
        return cardCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_company.card_company_name
     *
     * @param cardCompanyName the value for card_company.card_company_name
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setCardCompanyName(String cardCompanyName) {
        this.cardCompanyName = cardCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_company.prefecture
     *
     * @return the value of card_company.prefecture
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_company.prefecture
     *
     * @param prefecture the value for card_company.prefecture
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }
}