package vn.com.vti.springexam.entity;

public class OrderDetail extends OrderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.item_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.item_num
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private Integer itemNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.item_id
     *
     * @return the value of order_detail.item_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.item_id
     *
     * @param itemId the value for order_detail.item_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.item_num
     *
     * @return the value of order_detail.item_num
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.item_num
     *
     * @param itemNum the value for order_detail.item_num
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }
}