package vn.com.vti.springexam.entity;

public class OrderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private Integer orderDetailNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_no
     *
     * @return the value of order_detail.order_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_no
     *
     * @param orderNo the value for order_detail.order_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_no
     *
     * @return the value of order_detail.order_detail_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Integer getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_no
     *
     * @param orderDetailNo the value for order_detail.order_detail_no
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setOrderDetailNo(Integer orderDetailNo) {
        this.orderDetailNo = orderDetailNo;
    }
}