package vn.com.vti.springexam.entity;

public class Questionnaire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String questionnaireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.q_text1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String qText1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.q_text2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String qText2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire.q_text3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String qText3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.questionnaire_id
     *
     * @return the value of questionnaire.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.questionnaire_id
     *
     * @param questionnaireId the value for questionnaire.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.q_text1
     *
     * @return the value of questionnaire.q_text1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getqText1() {
        return qText1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.q_text1
     *
     * @param qText1 the value for questionnaire.q_text1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setqText1(String qText1) {
        this.qText1 = qText1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.q_text2
     *
     * @return the value of questionnaire.q_text2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getqText2() {
        return qText2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.q_text2
     *
     * @param qText2 the value for questionnaire.q_text2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setqText2(String qText2) {
        this.qText2 = qText2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire.q_text3
     *
     * @return the value of questionnaire.q_text3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getqText3() {
        return qText3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire.q_text3
     *
     * @param qText3 the value for questionnaire.q_text3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setqText3(String qText3) {
        this.qText3 = qText3;
    }
}