package vn.com.vti.springexam.entity;

public class QuestionnaireAnswerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.member_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String questionnaireId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.member_id
     *
     * @return the value of questionnaire_answer.member_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.member_id
     *
     * @param memberId the value for questionnaire_answer.member_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.questionnaire_id
     *
     * @return the value of questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.questionnaire_id
     *
     * @param questionnaireId the value for questionnaire_answer.questionnaire_id
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setQuestionnaireId(String questionnaireId) {
        this.questionnaireId = questionnaireId;
    }
}