package vn.com.vti.springexam.entity;

import java.util.ArrayList;
import java.util.List;

public class QuestionnaireExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public QuestionnaireExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionnaireIdIsNull() {
            addCriterion("questionnaire_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdIsNotNull() {
            addCriterion("questionnaire_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdEqualTo(String value) {
            addCriterion("questionnaire_id =", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdNotEqualTo(String value) {
            addCriterion("questionnaire_id <>", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdGreaterThan(String value) {
            addCriterion("questionnaire_id >", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdGreaterThanOrEqualTo(String value) {
            addCriterion("questionnaire_id >=", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdLessThan(String value) {
            addCriterion("questionnaire_id <", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdLessThanOrEqualTo(String value) {
            addCriterion("questionnaire_id <=", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdLike(String value) {
            addCriterion("questionnaire_id like", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdNotLike(String value) {
            addCriterion("questionnaire_id not like", value, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdIn(List<String> values) {
            addCriterion("questionnaire_id in", values, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdNotIn(List<String> values) {
            addCriterion("questionnaire_id not in", values, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdBetween(String value1, String value2) {
            addCriterion("questionnaire_id between", value1, value2, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQuestionnaireIdNotBetween(String value1, String value2) {
            addCriterion("questionnaire_id not between", value1, value2, "questionnaireId");
            return (Criteria) this;
        }

        public Criteria andQText1IsNull() {
            addCriterion("q_text1 is null");
            return (Criteria) this;
        }

        public Criteria andQText1IsNotNull() {
            addCriterion("q_text1 is not null");
            return (Criteria) this;
        }

        public Criteria andQText1EqualTo(String value) {
            addCriterion("q_text1 =", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1NotEqualTo(String value) {
            addCriterion("q_text1 <>", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1GreaterThan(String value) {
            addCriterion("q_text1 >", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1GreaterThanOrEqualTo(String value) {
            addCriterion("q_text1 >=", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1LessThan(String value) {
            addCriterion("q_text1 <", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1LessThanOrEqualTo(String value) {
            addCriterion("q_text1 <=", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1Like(String value) {
            addCriterion("q_text1 like", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1NotLike(String value) {
            addCriterion("q_text1 not like", value, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1In(List<String> values) {
            addCriterion("q_text1 in", values, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1NotIn(List<String> values) {
            addCriterion("q_text1 not in", values, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1Between(String value1, String value2) {
            addCriterion("q_text1 between", value1, value2, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText1NotBetween(String value1, String value2) {
            addCriterion("q_text1 not between", value1, value2, "qText1");
            return (Criteria) this;
        }

        public Criteria andQText2IsNull() {
            addCriterion("q_text2 is null");
            return (Criteria) this;
        }

        public Criteria andQText2IsNotNull() {
            addCriterion("q_text2 is not null");
            return (Criteria) this;
        }

        public Criteria andQText2EqualTo(String value) {
            addCriterion("q_text2 =", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2NotEqualTo(String value) {
            addCriterion("q_text2 <>", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2GreaterThan(String value) {
            addCriterion("q_text2 >", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2GreaterThanOrEqualTo(String value) {
            addCriterion("q_text2 >=", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2LessThan(String value) {
            addCriterion("q_text2 <", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2LessThanOrEqualTo(String value) {
            addCriterion("q_text2 <=", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2Like(String value) {
            addCriterion("q_text2 like", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2NotLike(String value) {
            addCriterion("q_text2 not like", value, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2In(List<String> values) {
            addCriterion("q_text2 in", values, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2NotIn(List<String> values) {
            addCriterion("q_text2 not in", values, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2Between(String value1, String value2) {
            addCriterion("q_text2 between", value1, value2, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText2NotBetween(String value1, String value2) {
            addCriterion("q_text2 not between", value1, value2, "qText2");
            return (Criteria) this;
        }

        public Criteria andQText3IsNull() {
            addCriterion("q_text3 is null");
            return (Criteria) this;
        }

        public Criteria andQText3IsNotNull() {
            addCriterion("q_text3 is not null");
            return (Criteria) this;
        }

        public Criteria andQText3EqualTo(String value) {
            addCriterion("q_text3 =", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3NotEqualTo(String value) {
            addCriterion("q_text3 <>", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3GreaterThan(String value) {
            addCriterion("q_text3 >", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3GreaterThanOrEqualTo(String value) {
            addCriterion("q_text3 >=", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3LessThan(String value) {
            addCriterion("q_text3 <", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3LessThanOrEqualTo(String value) {
            addCriterion("q_text3 <=", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3Like(String value) {
            addCriterion("q_text3 like", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3NotLike(String value) {
            addCriterion("q_text3 not like", value, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3In(List<String> values) {
            addCriterion("q_text3 in", values, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3NotIn(List<String> values) {
            addCriterion("q_text3 not in", values, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3Between(String value1, String value2) {
            addCriterion("q_text3 between", value1, value2, "qText3");
            return (Criteria) this;
        }

        public Criteria andQText3NotBetween(String value1, String value2) {
            addCriterion("q_text3 not between", value1, value2, "qText3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 12 16:45:37 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questionnaire
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}