package vn.com.vti.springexam.entity;

public class QuestionnaireAnswer extends QuestionnaireAnswerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String answer1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String answer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionnaire_answer.answer3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    private String answer3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer1
     *
     * @return the value of questionnaire_answer.answer1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getAnswer1() {
        return answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer1
     *
     * @param answer1 the value for questionnaire_answer.answer1
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setAnswer1(String answer1) {
        this.answer1 = answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer2
     *
     * @return the value of questionnaire_answer.answer2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getAnswer2() {
        return answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer2
     *
     * @param answer2 the value for questionnaire_answer.answer2
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setAnswer2(String answer2) {
        this.answer2 = answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionnaire_answer.answer3
     *
     * @return the value of questionnaire_answer.answer3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public String getAnswer3() {
        return answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionnaire_answer.answer3
     *
     * @param answer3 the value for questionnaire_answer.answer3
     *
     * @mbg.generated Mon Sep 12 16:45:37 JST 2022
     */
    public void setAnswer3(String answer3) {
        this.answer3 = answer3;
    }
}